data:
  for_trainNval: CIFAR100
  for_test: CIFAR100

  target_for_trainNval: True  # 라쏘 프루닝때도 적용됨
  target_for_test: True  # 테스트

  train:
    augmentation: null
    batch_size: 128
    n_workers: 8
    pin_memory: true
    shuffle: true
  val:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  test:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  target_classes: [0, 1, 2, 3, 4]

network: 
  model: resnet34
  load_state: models/pretrained/resnet34_cifar100.pt
  
  pruning:
    k: 0.30
    process_num: 3
    all_classes: True  # 기본 compress: True ,  saved_index 관련 없음          
    lasso:
      saved_index: # experiments/lasso_r34_cifar100_012/total_indices_stayed.pt
      # batch: 512

run:
  seed: 9099
  gpu_device: 1
  epoch: 50
  figure_interval: 50
  plot_interval: 10
  print_interval: 10
  val_interval: 25

  loss: crossentropy
  optimizer:
    lr: 5.0e-5
    name: adam
    momentum: 0.9
    milestones: [5, 10,15]
    gamma: 0.9
    weight_decay: 0.0005
    