data:
  for_trainNval: CIFAR100
  for_test: CIFAR100

  target_for_trainNval: False  # 라쏘 프루닝때도 적용됨
  target_for_test: False  # 테스트

  train:
    augmentation: null
    batch_size: 128
    n_workers: 8
    pin_memory: true
    shuffle: true
  val:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  test:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  target_classes: [95, 96, 97, 98, 99]

network: 
  model: resnet34
  load_state: #"models/pretrained/resnet34_cifar100.pt"

run:
  seed: 9099
  gpu_device: 7
  epoch: 120
  figure_interval: 50
  plot_interval: 10
  print_interval: 10
  val_interval: 20

  loss: crossentropy
  optimizer:
    lr: 1.0e-2
    name: adam
    momentum: 0.9
    milestones: [15, 30, 45, 60, 75, 90]
    gamma: 0.5
    weight_decay: 0.0005
    