data:
  for_trainNval: CIFAR100
  for_test: CIFAR100

  target_for_trainNval: False  # 라쏘 프루닝때도 적용됨
  target_for_test: True  # 테스트

  train:
    augmentation: null
    batch_size: 128
    n_workers: 8
    pin_memory: true
    shuffle: true
  val:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  test:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  target_classes: [0, 1, 2, 3, 4]

network: 
  model: resnet34
  load_state: models/pretrained/resnet34_cifar100.pt
  
  pruning:
    k: 0.05
    process_num: 6
    all_classes: False  # 프루닝에서만 all로 할때         
    iterative_lasso: True
    lasso:
      saved_index_0: experiments/iasso_aall_005_6_stoped_0/total_indices_stayed_0.pt
      # batch: 512

run:
  seed: 9099
  gpu_device: 1
  epoch: 15
  iter_num: 6
  figure_interval: 50
  plot_interval: 10
  print_interval: 5
  val_interval: 5

  loss: crossentropy
  optimizer:
    lr: 1.0e-4
    name: adam
    momentum: 0.9
    milestones: [5, 10,15]
    gamma: 0.9
    weight_decay: 0.0005
    