data:
  dir: CIFAR100
  train:
    augmentation: null
    batch_size: 128
    n_workers: 8
    pin_memory: true
    shuffle: true
  val:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  test:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false

  target_classes: [0, 1, 2, 3, 4]

network:
  backbone: resnet20

run:
  load_state: experiments/cifar100_res20_100epo/best_model.pt
  pruning: random
  lasso:
    all_classes: True  # 기본 lasso compress, saved_index 관련 없음
    k: 0.49
    # batch: 512
    saved_index: #experiments/lasso_one_batch/total_indices_stayed.pt
  
  seed: 9099
  gpu_device: 1
  epoch: 30
  figure_interval: 10
  plot_interval: 10
  print_interval: 10
  val_interval: 10
  loss: crossentropy
  optimizer:
    lr: 1.0e-4
    name: adam
    momentum: 0.9
    milestones: [5, 10,15]
    gamma: 0.9
    weight_decay: 0.0005
    