data:
  for_trainNval: CIFAR100
  for_test: CIFAR100

  train:
    augmentation: null
    batch_size: 128
    n_workers: 8
    pin_memory: true
    shuffle: true
  val:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  test:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  target_classes: [0, 1, 2]

network: 
  model: resnet34
  load_state: models/pretrained/resnet34_cifar100.pt
  
  pruning:
    k: 0.49
    all_classes: False  # 기본 compress: True ,  saved_index 관련 없음          
    lasso:
      saved_index: # experiments/lasso_r34_cifar100_012/total_indices_stayed.pt
      # batch: 512

run:
  seed: 9099
  gpu_device: 1
  epoch: 30
  iter_num: 6
  figure_interval: 50
  plot_interval: 10
  print_interval: 1
  val_interval: 5

  loss: crossentropy
  optimizer:
    lr: 1.0e-4
    name: adam
    momentum: 0.9
    milestones: [5, 10,15]
    gamma: 0.9
    weight_decay: 0.0005
    