data:
  dir: "CIFAR100" # directory path or "CIFAR10" or "CIFAR100"
  resize: 32 # Resize factor, integer number
  # Sampling options for dataloader
  train:
    augmentation:
      sift:   # circle   or   default   or   blur_circle
      edge: 
      gabor: 
      perspective: # True or False
    shuffle: True
    batch_size: 32
    n_workers: 2
    pin_memory: True
  val:
    shuffle: False
    batch_size: 128
    n_workers: 1
    pin_memory: True
  test:
    shuffle: False
    batch_size: 1
    n_workers: 1
    pin_memory: True

network:
  backbone: "resnet18"

run:
  epoch: 100
  val_interval: 5
  print_interval: 1
  loss: crossentropy
  optimizer:
    name: "adam"
    lr: 1.0e-2
  scheduler: # use this if neccessary