data:
  dir: CIFAR100
  train:
    augmentation: null
    batch_size: 128
    n_workers: 8
    pin_memory: true
    shuffle: true
  val:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  test:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false

network:
  backbone: resnet56

run:
  load_state: null
  
  epoch: 200
  figure_interval: 100
  plot_interval: 10
  print_interval: 10
  val_interval: 30
  loss: crossentropy
  optimizer:
    lr: 1.0e-4
    name: adam