data:
  dir: "CIFAR100" # directory path or "CIFAR10" or "CIFAR100"
  resize: 32 # Resize factor, integer number
  train:
    augmentation:
    shuffle: True
    batch_size: 128
    n_workers: 4
    pin_memory: True
  val:
    shuffle: False
    batch_size: 64
    n_workers: 1
    pin_memory: True
  test:
    shuffle: False
    batch_size: 1
    n_workers: 1
    pin_memory: True

network:
  backbone: "resnet20"

run:
  load_state:
  loss: crossentropy
  optimizer:
    name: "adam"
    lr: 5.0e-4
    
  epoch: 2
  val_interval: 1
  print_interval: 1
  plot_interval: 1
  figure_interval: 1