data:
  for_test: IMAGENET
  for_trainNval: IMAGENET
  target_classes:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  target_for_test: true
  target_for_trainNval: true
  test:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
  train:
    augmentation: null
    batch_size: 128
    n_workers: 8
    pin_memory: true
    shuffle: true
  val:
    batch_size: 128
    n_workers: 4
    pin_memory: true
    shuffle: false
network:
  load_state: models/pretrained/vgg16_bn_imagenet_50.pt
  model: vgg_16_bn
  pruning:
    all_classes: false
    k: 0.6
    lasso:
      saved_index: null
run:
  epoch: 120
  figure_interval: 50
  gpu_device: 7
  loss: crossentropy
  optimizer:
    gamma: 0.5
    lr: 0.01
    milestones:
    - 15
    - 30
    - 45
    - 60
    - 75
    - 90
    momentum: 0.9
    name: adam
    weight_decay: 0.0005
  plot_interval: 10
  print_interval: 10
  seed: 9099
  val_interval: 20
